version: 2

jobs:
  asterius-build-docker:
    docker:
      - image: docker:edge-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Make docker image
          command: |
            export ASTERIUS_REV=$(git rev-parse --short HEAD)
            docker login -u terrorjack -p $DOCKER_PASS
            docker build -t terrorjack/asterius:$ASTERIUS_REV -t terrorjack/asterius:$CIRCLE_BRANCH -t terrorjack/asterius:latest .

            docker start -a $(docker create terrorjack/asterius:$ASTERIUS_REV stack --no-terminal test asterius:fib --test-arguments="--debug")
            docker start -a $(docker create terrorjack/asterius:$ASTERIUS_REV stack --no-terminal test asterius:fib --test-arguments="--optimize")
            docker start -a $(docker create terrorjack/asterius:$ASTERIUS_REV stack --no-terminal test asterius:jsffi --test-arguments="--debug")
            docker start -a $(docker create terrorjack/asterius:$ASTERIUS_REV stack --no-terminal test asterius:jsffi --test-arguments="--optimize")
            docker start -a $(docker create terrorjack/asterius:$ASTERIUS_REV stack --no-terminal test asterius:array --test-arguments="--debug")
            docker start -a $(docker create terrorjack/asterius:$ASTERIUS_REV stack --no-terminal test asterius:array --test-arguments="--optimize")

            docker push terrorjack/asterius:$ASTERIUS_REV
            docker push terrorjack/asterius:$CIRCLE_BRANCH
            if [ $CIRCLE_BRANCH = "master" ]; then
              docker push terrorjack/asterius:latest
            fi

  asterius-build-docs:
    docker:
      - image: ubuntu:bionic
    environment:
      DEBIAN_FRONTEND: noninteractive
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              git \
              mkdocs
      - checkout
      - run:
          name: Build & push docs
          command: |
            if [ -z `ssh-keygen -F github.com` ]; then
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            fi
            mkdocs build
            cd site
            touch .nojekyll
            git init
            git config user.email "cheng.shao@tweag.io"
            git config user.name "Shao Cheng"
            git checkout -b gh-pages
            git add --all
            git commit -q --message="Documentation of tweag/asterius@$CIRCLE_SHA1"
            git push git@github.com:tweag/asterius.git gh-pages --force


workflows:
  version: 2
  build:
    jobs:
      - asterius-build-docker
      - asterius-build-docs:
          requires:
            - asterius-build-docker
          filters:
            branches:
              only: master
